### ISSUE TITLE
Update to 2016h?

### ISSUE THREAD

**Issue by drblue** [orocrm/moment-timezone#1]
Hi there!

Is there any update planned for this package to the new 2016h timezone database from IANA.org? Turkey has scrapped going back to Standard Time on Oct 30 and will stay on DST (GMT+3) indefinitely.

**Comment by Grygir** [comment]
Hello,

Yes, we will update moment-timezone soon. And after that, we are going to mark this package as deprecated in favor of https://github.com/moment/moment-timezone/blob/develop/composer.json

**Comment by Grygir** [comment]
Added latest version 0.5.7 of moment-timezone
